"use client";

import { useEffect, useState } from "react";
type Board = { id: number; name: string; description?: string }; type Stage = { id: number; board_id: number; name: string; position: number; deal_id?: number | null; deal_name?: string | null; amount?: number | string | null; contact_name?: string | null };
export default function CrmClient() { const [boards, setBoards] = useState<Board[]>([]); const [stages, setStages] = useState<Stage[]>([]); const [form, setForm] = useState({ name: "", amount: "" }); const [message, setMessage] = useState("");
  async function load() { const res = await fetch("/api/crm/boards", { cache: "no-store" }); const data = await res.json(); if (res.ok) { setBoards(data.boards); setStages(data.stages); } }
  useEffect(() => { void load(); }, []);
  async function create(event: React.FormEvent) { event.preventDefault(); const board = boards[0]; const stage = stages.find((item) => item.board_id === board?.id); if (!board || !stage) return; const res = await fetch("/api/crm/deals", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ board_id: board.id, stage_id: stage.id, name: form.name, amount: Number(form.amount || 0) }) }); const data = await res.json(); if (!res.ok) { setMessage(data.error ?? "Erro ao criar negócio."); return; } setForm({ name: "", amount: "" }); setMessage("Negócio criado na primeira etapa."); await load(); }
  const board = boards[0]; const columns = stages.filter((s) => s.board_id === board?.id).reduce<Record<number, Stage[]>>((acc, stage) => { (acc[stage.id] ||= []).push(stage); return acc; }, {});
  return <><section className="panel form-panel"><h3>Novo negócio</h3><form className="form-grid" onSubmit={create}><input placeholder="Nome do negócio" required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><input placeholder="Valor" type="number" min="0" step="0.01" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} /><div className="form-actions"><button className="button">Adicionar ao funil</button>{message && <span className="muted">{message}</span>}</div></form></section><div className="kanban">{!board ? <div className="empty">Nenhum quadro disponível.</div> : stages.filter((stage) => stage.board_id === board.id).sort((a, b) => a.position - b.position).map((stage) => <section className="kanban-column" key={stage.id}><h3>{stage.name}</h3>{(columns[stage.id] || []).filter((item) => item.deal_id).map((deal) => <article className="deal-card" key={deal.deal_id}><strong>{deal.deal_name}</strong><small>{deal.contact_name || "Sem contato"}<br />R$ {Number(deal.amount || 0).toFixed(2)}</small></article>)}</section>)}</div></>;
}
