"use client";

import { useEffect, useState } from "react";
type Connection = { public_id: string; name: string; instance_name: string; status: string };
export default function ConnectionsClient({ canManage }: { canManage: boolean }) { const [items, setItems] = useState<Connection[]>([]); const [name, setName] = useState(""); const [message, setMessage] = useState(""); const [qr, setQr] = useState("");
  async function load() { const res = await fetch("/api/integrations/evolution/connections", { cache: "no-store" }); const data = await res.json(); if (res.ok) setItems(data.connections); }
  useEffect(() => { void load(); }, []);
  async function create(event: React.FormEvent) { event.preventDefault(); setMessage(""); const res = await fetch("/api/integrations/evolution/connections", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name }) }); const data = await res.json(); if (!res.ok) { setMessage(data.error ?? "Não foi possível criar."); return; } setName(""); setMessage("Conexão criada. Use Conectar para gerar o QR Code."); await load(); }
  async function connect(id: string) { setMessage(""); const res = await fetch(`/api/integrations/evolution/connections/${id}/connect`, { method: "POST" }); const data = await res.json(); if (!res.ok) { setMessage(data.error ?? "Falha ao conectar."); return; } setQr(data.qrcode || ""); setMessage(data.pairing_code ? `Código de pareamento: ${data.pairing_code}` : "QR Code gerado."); await load(); }
  async function status(id: string) { const res = await fetch(`/api/integrations/evolution/connections/${id}/status`, { cache: "no-store" }); const data = await res.json(); if (res.ok) { setMessage(`Status: ${data.status}`); await load(); } }
  return <><section className="panel form-panel">{canManage ? <form className="toolbar" onSubmit={create}><input placeholder="Nome da conexão" required value={name} onChange={(e) => setName(e.target.value)} /><button className="button">Adicionar WhatsApp</button></form> : <p className="muted">Somente administradores podem criar conexões.</p>}{message && <p className="muted">{message}</p>}{qr && <img className="qr" src={qr.startsWith("data:") ? qr : `data:image/png;base64,${qr}`} alt="QR Code para conectar o WhatsApp" />}</section><section className="table-card">{items.length === 0 ? <div className="empty">Nenhuma conexão cadastrada.</div> : <table className="data-table"><thead><tr><th>Nome</th><th>Instância</th><th>Status</th><th>Ações</th></tr></thead><tbody>{items.map((item) => <tr key={item.public_id}><td>{item.name}</td><td>{item.instance_name}</td><td>{item.status}</td><td>{canManage && <><button className="button secondary" onClick={() => connect(item.public_id)}>Conectar</button> <button className="button secondary" onClick={() => status(item.public_id)}>Atualizar</button></>}</td></tr>)}</tbody></table>}</section></>;
}
