"use client";

import { useEffect, useState } from "react";
type Conversation = { id: number; contact_name: string; contact_phone: string; unread_count: number; last_message_at?: string | null }; type Message = { id: number; direction: "inbound" | "outbound"; content: string; created_at: string };
export default function ConversationsClient() { const [items, setItems] = useState<Conversation[]>([]); const [selected, setSelected] = useState<number | null>(null); const [messages, setMessages] = useState<Message[]>([]); const [text, setText] = useState(""); const [message, setMessage] = useState("");
  async function load() { const res = await fetch("/api/conversations", { cache: "no-store" }); const data = await res.json(); if (res.ok) { setItems(data.conversations); if (selected === null && data.conversations[0]) setSelected(data.conversations[0].id); } }
  async function loadMessages(id: number) { const res = await fetch(`/api/conversations/${id}/messages`, { cache: "no-store" }); const data = await res.json(); if (res.ok) setMessages(data.messages); }
  useEffect(() => { void load(); }, []); useEffect(() => { if (selected) void loadMessages(selected); }, [selected]);
  async function send(event: React.FormEvent) { event.preventDefault(); if (!selected || !text.trim()) return; const res = await fetch(`/api/conversations/${selected}/messages`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ content: text }) }); const data = await res.json(); if (!res.ok) { setMessage(data.error ?? "Não foi possível enviar."); return; } setText(""); setMessage(""); await loadMessages(selected); }
  return <section className="panel chat-layout"><div className="conversation-list">{items.length === 0 ? <div className="empty">Nenhuma conversa recebida.</div> : items.map((item) => <button className={`conversation-item ${selected === item.id ? "active" : ""}`} key={item.id} onClick={() => setSelected(item.id)}><strong>{item.contact_name}</strong><span>{item.contact_phone} {item.unread_count ? `· ${item.unread_count} nova(s)` : ""}</span></button>)}</div><div className="chat-panel"><div className="chat-messages">{!selected ? <div className="empty">Selecione uma conversa.</div> : messages.map((item) => <div className={`bubble ${item.direction}`} key={item.id}>{item.content}</div>)}</div>{selected && <form className="composer" onSubmit={send}><input aria-label="Mensagem" placeholder="Digite uma mensagem" value={text} onChange={(e) => setText(e.target.value)} /><button className="button">Enviar</button></form>}{message && <div className="error">{message}</div>}</div></section>;
}
