"use client";

import Link from "next/link";
import { use, useState } from "react";
import Turnstile from "@/components/turnstile";

export default function ResetPasswordPage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = use(params); const [password, setPassword] = useState(""); const [confirmation, setConfirmation] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [turnstileToken, setTurnstileToken] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); setMessage(""); if (password !== confirmation) { setError("As senhas não conferem."); return; } if (!turnstileToken) { setError("Confirme a verificação de segurança."); return; } setLoading(true); const response = await fetch(`/api/auth/reset-password/${encodeURIComponent(token)}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ password, turnstileToken }) }); const data = await response.json(); setLoading(false); if (!response.ok) { setError(data.error ?? "Link inválido ou expirado."); return; } setMessage("Senha alterada com sucesso. Você já pode entrar."); }
  return <main className="auth-page"><section className="auth-card"><div className="brand">CRM360</div><h1>Nova senha</h1><p className="muted">Escolha uma senha com pelo menos 12 caracteres.</p><form onSubmit={submit}><div className="field"><label htmlFor="password">Nova senha</label><input id="password" type="password" minLength={12} required value={password} onChange={(event) => setPassword(event.target.value)} /></div><div className="field"><label htmlFor="confirmation">Confirme a senha</label><input id="confirmation" type="password" minLength={12} required value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></div><Turnstile siteKey={process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY ?? ""} action="reset-password" onToken={setTurnstileToken} />{error && <div className="error" role="alert">{error}</div>}{message && <div className="notice" role="status">{message}</div>}<button className="primary-button" disabled={loading || Boolean(message)}>{loading ? "Salvando..." : "Salvar nova senha"}</button></form><div className="auth-footer"><Link href="/login">Voltar para o login</Link></div></section></main>;
}
