"use client";

import { useEffect, useState } from "react";

type Plan = { id: number; name: string; slug: string; description?: string | null; price_cents: number; max_users: number; max_connections: number; max_contacts: number; max_boards: number; max_deals: number; max_messages_month: number; active: boolean };
type Form = Omit<Plan, "id" | "active"> & { active: boolean };
const empty: Form = { name: "", slug: "", description: "", price_cents: 0, max_users: 3, max_connections: 1, max_contacts: 500, max_boards: 1, max_deals: 500, max_messages_month: 5000, active: true };
const limitLabels: Array<[keyof Form, string]> = [["max_users", "Usuários"], ["max_connections", "WhatsApp"], ["max_contacts", "Contatos"], ["max_boards", "Quadros"], ["max_deals", "Negócios"], ["max_messages_month", "Mensagens/mês"]];

export default function PlansClient() {
  const [plans, setPlans] = useState<Plan[]>([]); const [form, setForm] = useState<Form>(empty); const [editing, setEditing] = useState<number | null>(null); const [message, setMessage] = useState(""); const [open, setOpen] = useState(false);
  async function load() { const response = await fetch("/api/master/plans", { cache: "no-store" }); const data = await response.json(); if (response.ok) setPlans(data.plans); }
  useEffect(() => { void load(); }, []);
  function start(plan?: Plan) { setMessage(""); setOpen(true); setEditing(plan?.id ?? null); setForm(plan ? { name: plan.name, slug: plan.slug, description: plan.description ?? "", price_cents: plan.price_cents, max_users: plan.max_users, max_connections: plan.max_connections, max_contacts: plan.max_contacts, max_boards: plan.max_boards, max_deals: plan.max_deals, max_messages_month: plan.max_messages_month, active: plan.active } : empty); }
  function update(field: keyof Form, value: string | boolean) { setForm({ ...form, [field]: value }); }
  async function save(event: React.FormEvent) { event.preventDefault(); setMessage(""); const url = editing ? `/api/master/plans/${editing}` : "/api/master/plans"; const response = await fetch(url, { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) { setMessage(data.error ?? "Não foi possível salvar o plano."); return; } setOpen(false); setEditing(null); setMessage("Plano salvo."); await load(); window.dispatchEvent(new Event("crm360-plans-updated")); }
  async function remove(plan: Plan) { if (!window.confirm(`Excluir o plano ${plan.name}?`)) return; const response = await fetch(`/api/master/plans/${plan.id}`, { method: "DELETE" }); const data = await response.json(); if (!response.ok) { setMessage(data.error ?? "Não foi possível excluir o plano."); return; } await load(); window.dispatchEvent(new Event("crm360-plans-updated")); }
  return <section className="master-plans"><div className="master-plans-heading"><div><p className="master-kicker">Modelo comercial</p><h2>Planos e limites</h2><p>Defina o que cada empresa pode utilizar. <strong>0 significa ilimitado.</strong></p></div><button className="master-button primary" onClick={() => start()}><span className="material-symbols-rounded">add</span> Novo plano</button></div>{message && <div className="master-message">{message}</div>}{open && <form className="master-plan-form" onSubmit={save}><div className="master-plan-form-top"><h3>{editing ? "Editar plano" : "Novo plano"}</h3><button type="button" className="master-plan-close" onClick={() => setOpen(false)}>Fechar</button></div><div className="master-plan-fields"><input placeholder="Nome do plano" required value={form.name} onChange={(event) => update("name", event.target.value)} /><input placeholder="slug-exemplo" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value={form.slug} onChange={(event) => update("slug", event.target.value)} /><input placeholder="Descrição curta (opcional)" value={form.description ?? ""} onChange={(event) => update("description", event.target.value)} /><input type="number" min="0" placeholder="Preço em centavos" value={form.price_cents} onChange={(event) => update("price_cents", event.target.value)} />{limitLabels.map(([field, label]) => <label key={field}>{label}<input type="number" min="0" value={String(form[field])} onChange={(event) => update(field, event.target.value)} /></label>)}</div><label className="master-plan-active"><input type="checkbox" checked={form.active} onChange={(event) => update("active", event.target.checked)} /> Plano ativo para novas atribuições</label><button className="master-button primary">Salvar plano</button></form>}<div className="master-plan-cards">{plans.length === 0 ? <div className="master-empty">Nenhum plano criado.</div> : plans.map((plan) => <article className={`master-plan-card ${plan.active ? "" : "inactive"}`} key={plan.id}><div className="master-plan-card-heading"><div><h3>{plan.name}</h3><span>{plan.description || plan.slug}</span></div><span className={`master-status ${plan.active ? "master-status-active" : "master-status-inactive"}`}>{plan.active ? "Ativo" : "Inativo"}</span></div><strong className="master-plan-price">{plan.price_cents ? `R$ ${(plan.price_cents / 100).toFixed(2).replace(".", ",")}` : "Grátis"}<small>/mês</small></strong><div className="master-plan-limits">{limitLabels.map(([field, label]) => <span key={field}><strong>{plan[field] === 0 ? "∞" : String(plan[field])}</strong>{label}</span>)}</div><div className="master-plan-actions"><button className="master-button" onClick={() => start(plan)}>Editar</button><button className="master-plan-delete" onClick={() => remove(plan)}>Excluir</button></div></article>)}</div></section>;
}
